
name: 编译openwrt1.0

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: 切换到master分支开始编译
        uses: actions/checkout@master
        with:
          ref: master

      - name: 准备工作，下载必要的包等
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: 更新feeds源
        run: |
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
    
      - name: 配置文件
        run: |
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 编译预下载
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: 开始编译openwrt
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: 准备编译后的文件
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: 编译结果
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
